version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  server:
    container_name: budget-server
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - server_node_modules:/server/node_modules
    environment:
      - NODE_ENV=production
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "start"]
    depends_on:
      - rabbitmq

  client:
    container_name: budget-client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - client_node_modules:/client/node_modules
    command: npm start
    environment:
      - NODE_ENV=production

volumes:
  rabbitmq_data:
  client_node_modules:
  server_node_modules: