export enum ErrorNames {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR",
  UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
  ALREADY_EXISTS_ERROR = "ALREADY_EXISTS_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  FORBIDDEN_ERROR = "FORBIDDEN_ERROR",
}
