export enum SettingNames {
  PORT = "PORT",
  RABBITMQ_URI = "RABBITMQ_URI",
  DB_URI = "DB_URI",
  DB_NAME = "DB_NAME",
  TOKEN_KEY = "TOKEN_KEY",
  TOKEN_EXPIRES_IN = "TOKEN_EXPIRES_IN",
  GA_TRACKING_ID = "GA_TRACKING_ID",
}
